### ISSUE TITLE
[Bug]: Restore Local QA Rust CI after PR #6057

### ISSUE THREAD

**Issue by wanghuan-520** [ChronoAIProject/fkst-hosted#6059]
## Summary

PR #6057 merged the Local QA Executor expand step into `feat/local-qa-runtime`, but the resulting branch does not compile and fails rustfmt. Restore the branch to green without changing the Executor contract design or the control-plane auto-merge behavior.

## Scope Check

- [x] This bug is within **fkst-hosted** scope: Local QA Runtime and shared QA contracts.

## Affected Area

- [x] Local QA Runtime (Rust)
- [x] Shared QA contracts (Rust)

## Environment

- Branch / commit: `feat/local-qa-runtime` at merge commit `fe66057492f48c9c9b8f5461578832863ba9bfec`
- Introduced by: PR #6057
- Failed workflow: Rust CI run `32805878052`

## Steps to Reproduce

1. Check out `feat/local-qa-runtime` at or after `fe66057492f48c9c9b8f5461578832863ba9bfec`.
2. Run `cargo fmt --manifest-path apps/local-qa-runtime/Cargo.toml --all -- --check`.
3. Run `cargo build --manifest-path apps/local-qa-runtime/Cargo.toml --workspace --locked`.
4. Run `cargo test --manifest-path apps/local-qa-runtime/Cargo.toml --workspace --locked -- --nocapture`.

## Expected Behavior

- Local QA Runtime rustfmt, build, clippy, and tests pass.
- The `qa.local-executor/v1` Rust digest relation validator compiles and retains the exact `sha256:<lowercase hex>` behavior used by the shared fixtures.

## Actual Behavior

- `packages/qa-contracts/rust/src/lib.rs:874` calls undefined function `hex_digest`, producing `error[E0425]` and preventing `fkst-qa-contracts` from compiling.
- `cargo fmt --check` reports formatting diffs in `apps/local-qa-runtime/host/src/executor.rs`, `apps/local-qa-runtime/host/src/lib.rs`, and `packages/qa-contracts/rust/src/lib.rs`.

## Required Fix

- Replace the undefined digest call with the existing, correct `sha256_digest` path or an equivalently minimal implementation; do not duplicate digest policy.
- Apply repository rustfmt to the touched Rust files.
- Preserve the exact Browser/API digest vectors and all behavior introduced by #6057.
- Add or retain a focused regression assertion that recomputes and checks the expected `sha256:` capability digest.

## Acceptance Criteria

- [ ] `cargo fmt --manifest-path apps/local-qa-runtime/Cargo.toml --all -- --check` passes.
- [ ] `cargo clippy --manifest-path apps/local-qa-runtime/Cargo.toml --workspace --all-targets --locked -- -D warnings` passes.
- [ ] `cargo build --manifest-path apps/local-qa-runtime/Cargo.toml --workspace --locked` passes.
- [ ] `cargo test --manifest-path apps/local-qa-runtime/Cargo.toml --workspace --locked -- --nocapture` passes.
- [ ] QA contracts TypeScript type-check/build/test remain green.
- [ ] No workflow, branch-protection, auto-merge, #5855, or unrelated Runtime behavior changes are included.
- [ ] The implementation PR targets `feat/local-qa-runtime` and closes this issue.

## Additional Context

- `sha256_digest(bytes: &[u8]) -> String` already exists in `packages/qa-contracts/rust/src/lib.rs` and returns the complete `sha256:<lowercase hex>` string.
- #6058 was declined because its pinned checkout did not contain the merged Expand artifacts; this repair must only restore the Expand baseline to green.

**Comment by wanghuan-520** [comment]
fkst: reimplement

Operator liveness recovery: the approved CI repair has remained in `implementing` for more than 45 minutes with no implementation output, commit, or PR. Restart implementation from the latest `feat/local-qa-runtime` head while preserving the bounded scope: replace the undefined digest helper through the existing `sha256_digest` authority, apply rustfmt, and restore the existing Rust/TypeScript checks without changing workflow, auto-merge, #5855, or Executor contract semantics.
