### ISSUE TITLE
[Bug]: Restore Local QA Rust CI after PR #5970

### ISSUE THREAD

**Issue by wanghuan-520** [ChronoAIProject/fkst-hosted#5971]
## Summary

Restore the Local QA Runtime Rust checks after PR #5970 introduced a compile error and unformatted Rust sources on `feat/local-qa-runtime`.

## Problem / Motivation

PR #5970 merged into `feat/local-qa-runtime`, but its CI reported:

- `rust lint`: `cargo fmt --all -- --check` failed in the Evidence stager sources and tests.
- `rust build`: `apps/local-qa-runtime/evidence-stager/src/lib.rs:530` fails with `error[E0308]`; `Ok(()) => current.pop()` returns `bool` where the match arm must return `()`.
- `rust test`: the backend tests pass, but the Local QA workspace cannot compile because of the same E0308.

This issue is limited to restoring the already-implemented Evidence hardening build surface. Do not change the auto-merge implementation, branch rules, #5855, or unrelated behavior.

## Scope

Primary files:

- `apps/local-qa-runtime/evidence-stager/src/lib.rs`
- `apps/local-qa-runtime/evidence-stager/tests/browser_screenshot.rs`
- `apps/local-qa-runtime/evidence-stager/tests/runner_log.rs`

Required changes:

- Fix `remove_empty_parents` so the `Ok(())` arm explicitly discards the `PathBuf::pop()` boolean and returns unit.
- Apply repository rustfmt to the affected Evidence stager source and tests.
- Do not weaken the quota, containment, verification, cleanup, residual, or duplicate-identity behavior introduced by #5969.

## Acceptance Criteria

- [ ] `cargo fmt --all -- --check` passes from `apps/local-qa-runtime`.
- [ ] `cargo build --manifest-path apps/local-qa-runtime/Cargo.toml --workspace --locked` passes.
- [ ] `cargo test --manifest-path apps/local-qa-runtime/Cargo.toml --workspace --locked -- --nocapture` passes.
- [ ] The focused Evidence stager tests continue to cover the #5969 behavior.
- [ ] No files outside the scoped Evidence stager source/tests are changed unless required by formatting.
- [ ] The resulting PR targets `feat/local-qa-runtime` and links this issue.

## Context

- Source PR: #5970
- Source implementation commit: `152eae4e7265c87b85628d4b0557a23a341bbec5`
- Failing compiler location: `apps/local-qa-runtime/evidence-stager/src/lib.rs:530`
- Target branch: `feat/local-qa-runtime`
